import { Pool as PgPool, type PoolClient, type QueryResult, types as pgTypes } from "pg";

type QueryParams = readonly unknown[] | undefined;
type MysqlCompatHeader = {
  affectedRows: number;
  changedRows: number;
  insertId: number;
  warningStatus: number;
  rowCount: number;
};

export type DatabaseConnection = {
  query<T = unknown>(sql: string, params?: QueryParams): Promise<[T, unknown[]]>;
  execute<T = unknown>(sql: string, params?: QueryParams): Promise<[T, unknown[]]>;
  beginTransaction(): Promise<void>;
  commit(): Promise<void>;
  rollback(): Promise<void>;
  release(): void;
};

export type DatabasePool = {
  query<T = unknown>(sql: string, params?: QueryParams): Promise<[T, unknown[]]>;
  execute<T = unknown>(sql: string, params?: QueryParams): Promise<[T, unknown[]]>;
  getConnection(): Promise<DatabaseConnection>;
  end(): Promise<void>;
};

const INT8_OID = 20;
pgTypes.setTypeParser(INT8_OID, (value) => {
  const parsed = Number(value);
  return Number.isSafeInteger(parsed) ? parsed : value;
});

const POSTGRES_TRANSIENT_CODES = new Set([
  "08000",
  "08003",
  "08006",
  "57P01",
  "57P02",
  "57P03",
  "53300",
]);

export const isPostgresTransientErrorCode = (code: string) => POSTGRES_TRANSIENT_CODES.has(code);

export const isPostgresDatabaseProvider = () => {
  const provider = (process.env.DATABASE_PROVIDER ?? "").trim().toLowerCase();
  const url = (process.env.DATABASE_URL ?? "").trim().toLowerCase();
  return provider === "postgres" || provider === "postgresql" || url.startsWith("postgres://") || url.startsWith("postgresql://");
};

const splitTopLevel = (value: string, separator = ",") => {
  const parts: string[] = [];
  let current = "";
  let depth = 0;
  let quote: "'" | "\"" | "`" | null = null;

  for (let index = 0; index < value.length; index += 1) {
    const char = value[index];
    const previous = index > 0 ? value[index - 1] : "";
    if (quote) {
      current += char;
      if (char === quote && previous !== "\\") {
        quote = null;
      }
      continue;
    }
    if (char === "'" || char === "\"" || char === "`") {
      quote = char;
      current += char;
      continue;
    }
    if (char === "(") depth += 1;
    if (char === ")") depth = Math.max(0, depth - 1);
    if (char === separator && depth === 0) {
      parts.push(current.trim());
      current = "";
      continue;
    }
    current += char;
  }
  if (current.trim()) parts.push(current.trim());
  return parts;
};

const quoteIdentifier = (value: string) => {
  const normalized = value.replace(/[`"]/g, "").trim();
  return `"${normalized.replace(/"/g, "\"\"")}"`;
};

const normalizeIdentifier = (value: string) => value.replace(/[`"]/g, "").trim();

const replaceBacktickIdentifiers = (sql: string) => sql.replace(/`([^`]+)`/g, (_match, name: string) => quoteIdentifier(name));

const stripMysqlClauses = (sql: string) =>
  sql
    .replace(/\)\s*ENGINE\s*=\s*InnoDB\s*;?/gi, ");")
    .replace(/\s+DEFAULT\s+CHARSET\s*=\s*\w+/gi, "")
    .replace(/\s+CHARACTER\s+SET\s+\w+/gi, "")
    .replace(/\s+COLLATE\s+\w+/gi, "");

const translateColumnDefinition = (definition: string) => {
  let sql = replaceBacktickIdentifiers(definition.trim());
  sql = sql.replace(/\b(BIGINT)\s+UNSIGNED\s+NOT\s+NULL\s+AUTO_INCREMENT\b/gi, "$1 GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(INT|INTEGER)\s+UNSIGNED\s+NOT\s+NULL\s+AUTO_INCREMENT\b/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(BIGINT)\s+NOT\s+NULL\s+AUTO_INCREMENT\b/gi, "$1 GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(INT|INTEGER)\s+NOT\s+NULL\s+AUTO_INCREMENT\b/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(BIGINT)\s+UNSIGNED\s+AUTO_INCREMENT\b/gi, "$1 GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(INT|INTEGER)\s+UNSIGNED\s+AUTO_INCREMENT\b/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(BIGINT)\s+AUTO_INCREMENT\b/gi, "$1 GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\b(INT|INTEGER)\s+AUTO_INCREMENT\b/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\bAUTO_INCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY");
  sql = sql.replace(/\bTINYINT\s*\(\s*1\s*\)/gi, "SMALLINT");
  sql = sql.replace(/\bTINYINT\b/gi, "SMALLINT");
  sql = sql.replace(/\bINT\s+UNSIGNED\b/gi, "INTEGER");
  sql = sql.replace(/\bBIGINT\s+UNSIGNED\b/gi, "BIGINT");
  sql = sql.replace(/\bSMALLINT\s+UNSIGNED\b/gi, "SMALLINT");
  sql = sql.replace(/\bUNSIGNED\b/gi, "");
  sql = sql.replace(/\bINT\b/gi, "INTEGER");
  sql = sql.replace(/\bDATETIME\b/gi, "TIMESTAMP");
  sql = sql.replace(/\b(LONGTEXT|MEDIUMTEXT|TINYTEXT)\b/gi, "TEXT");
  sql = sql.replace(/\bJSON\b/gi, "TEXT");
  sql = sql.replace(/\bENUM\s*\((?:[^)(]|\([^)]*\))*\)/gi, "TEXT");
  sql = sql.replace(/\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP(?:\s*\(\s*\d+\s*\))?/gi, "");
  sql = sql.replace(/\s+AFTER\s+"?[\w]+"?/gi, "");
  sql = sql.replace(/\bDEFAULT\s+TRUE\b/gi, "DEFAULT 1");
  sql = sql.replace(/\bDEFAULT\s+FALSE\b/gi, "DEFAULT 0");
  return sql;
};

const buildIndexName = (tableName: string, indexName: string) =>
  normalizeIdentifier(indexName || `${tableName}_idx`).replace(/[^\w]+/g, "_");

const translateCreateTable = (sql: string) => {
  const stripped = stripMysqlClauses(sql.trim());
  const match = stripped.match(/^\s*CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+([`"\w.]+)\s*\(/i);
  if (!match) {
    return { mainSql: translateGenericSql(stripped), afterSql: [] as string[] };
  }

  const tableToken = match[1];
  const tableName = normalizeIdentifier(tableToken.split(".").pop() ?? tableToken);
  const openIndex = stripped.indexOf("(", match.index ?? 0);
  let depth = 0;
  let closeIndex = -1;
  for (let index = openIndex; index < stripped.length; index += 1) {
    const char = stripped[index];
    if (char === "(") depth += 1;
    if (char === ")") {
      depth -= 1;
      if (depth === 0) {
        closeIndex = index;
        break;
      }
    }
  }
  if (openIndex < 0 || closeIndex < 0) {
    return { mainSql: translateGenericSql(stripped), afterSql: [] as string[] };
  }

  const body = stripped.slice(openIndex + 1, closeIndex);
  const afterSql: string[] = [];
  const definitions = splitTopLevel(body).flatMap((part) => {
    const trimmed = part.trim().replace(/,$/, "");
    if (!trimmed) return [];

    const uniqueKey = trimmed.match(/^UNIQUE\s+(?:KEY|INDEX)\s+([`"\w]+)\s*\((.+)\)$/i);
    if (uniqueKey) {
      return [`CONSTRAINT ${quoteIdentifier(uniqueKey[1])} UNIQUE (${replaceBacktickIdentifiers(uniqueKey[2])})`];
    }

    const constraintUnique = trimmed.match(/^CONSTRAINT\s+([`"\w]+)\s+UNIQUE\s+(?:KEY|INDEX)?\s*[`"\w]*\s*\((.+)\)$/i);
    if (constraintUnique) {
      return [`CONSTRAINT ${quoteIdentifier(constraintUnique[1])} UNIQUE (${replaceBacktickIdentifiers(constraintUnique[2])})`];
    }

    const plainIndex = trimmed.match(/^(?:KEY|INDEX)\s+([`"\w]+)\s*\((.+)\)$/i);
    if (plainIndex) {
      const indexName = buildIndexName(tableName, plainIndex[1]);
      afterSql.push(`CREATE INDEX IF NOT EXISTS ${quoteIdentifier(indexName)} ON ${quoteIdentifier(tableName)} (${replaceBacktickIdentifiers(plainIndex[2])})`);
      return [];
    }

    const primaryKey = trimmed.match(/^PRIMARY\s+KEY\s+\((.+)\)$/i);
    if (primaryKey) {
      return [`PRIMARY KEY (${replaceBacktickIdentifiers(primaryKey[1])})`];
    }

    if (/^CONSTRAINT\s+/i.test(trimmed) || /^FOREIGN\s+KEY\s+/i.test(trimmed)) {
      return [replaceBacktickIdentifiers(trimmed).replace(/\bUNIQUE\s+KEY\b/gi, "UNIQUE")];
    }

    return [translateColumnDefinition(trimmed)];
  });

  const mainSql = `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(tableName)} (\n  ${definitions.join(",\n  ")}\n)`;
  return { mainSql, afterSql };
};

const translateShowColumns = async (
  client: PoolClient,
  sql: string,
  params: readonly unknown[] = [],
) => {
  const match = sql.match(/SHOW\s+COLUMNS\s+FROM\s+([`"\w.]+)(?:\s+LIKE\s+(\?|'([^']+)'))?/i);
  if (!match) return null;
  const tableName = normalizeIdentifier(match[1].split(".").pop() ?? match[1]);
  const columnName = String(params[0] ?? match[3] ?? "");
  const values: unknown[] = [tableName];
  let where = "table_schema = current_schema() AND table_name = $1";
  if (columnName) {
    values.push(columnName);
    where += " AND column_name = $2";
  }
  const result = await client.query(
    `SELECT
       column_name AS "Field",
       CASE WHEN is_nullable = 'YES' THEN 'YES' ELSE 'NO' END AS "Null",
       data_type AS "Type",
       column_default AS "Default",
       '' AS "Key",
       CASE WHEN column_default LIKE 'nextval(%' THEN 'auto_increment' ELSE '' END AS "Extra"
     FROM information_schema.columns
     WHERE ${where}
     ORDER BY ordinal_position`,
    values,
  );
  return [result.rows, []] as [unknown, unknown[]];
};

const translateShowIndex = async (
  client: PoolClient,
  sql: string,
  params: readonly unknown[] = [],
) => {
  const match = sql.match(/SHOW\s+(?:INDEX|KEYS)\s+FROM\s+([`"\w.]+)/i);
  if (!match) return null;
  const tableName = normalizeIdentifier(match[1].split(".").pop() ?? match[1]);
  const keyName = /Key_name\s*=\s*\?/i.test(sql) ? String(params[0] ?? "") : null;
  const columnNameMatch = sql.match(/Column_name\s*=\s*'([^']+)'/i);
  const values: unknown[] = [tableName];
  let where = "t.relname = $1";
  if (keyName) {
    values.push(keyName);
    where += ` AND i.relname = $${values.length}`;
  }
  if (columnNameMatch) {
    values.push(columnNameMatch[1]);
    where += ` AND a.attname = $${values.length}`;
  }
  const result = await client.query(
    `SELECT
       i.relname AS "Key_name",
       a.attname AS "Column_name",
       CASE WHEN ix.indisunique THEN 0 ELSE 1 END AS "Non_unique",
       row_number() OVER (PARTITION BY i.relname ORDER BY array_position(ix.indkey, a.attnum)) AS "Seq_in_index"
     FROM pg_class t
     JOIN pg_index ix ON t.oid = ix.indrelid
     JOIN pg_class i ON i.oid = ix.indexrelid
     JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(ix.indkey)
     WHERE ${where}
     ORDER BY i.relname, "Seq_in_index"`,
    values,
  );
  return [result.rows, []] as [unknown, unknown[]];
};

const translateReferentialConstraints = async (client: PoolClient, sql: string) => {
  if (!/information_schema\.REFERENTIAL_CONSTRAINTS/i.test(sql)) return null;
  const tableName = sql.match(/\brc\.TABLE_NAME\s*=\s*'([^']+)'/i)?.[1];
  const referencedTableName = sql.match(/\brc\.REFERENCED_TABLE_NAME\s*=\s*'([^']+)'/i)?.[1];
  const columnName = sql.match(/\bkcu\.COLUMN_NAME\s*=\s*'([^']+)'/i)?.[1];
  if (!tableName || !referencedTableName || !columnName) return null;

  const result = await client.query(
    `SELECT
       c.conname AS constraint_name,
       CASE c.confdeltype
         WHEN 'c' THEN 'CASCADE'
         WHEN 'n' THEN 'SET NULL'
         WHEN 'd' THEN 'SET DEFAULT'
         WHEN 'r' THEN 'RESTRICT'
         ELSE 'NO ACTION'
       END AS delete_rule
     FROM pg_constraint c
     JOIN pg_class child ON child.oid = c.conrelid
     JOIN pg_class parent ON parent.oid = c.confrelid
     JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS ord(attnum, ordinality) ON true
     JOIN pg_attribute a ON a.attrelid = child.oid AND a.attnum = ord.attnum
     WHERE c.contype = 'f'
       AND child.relname = $1
       AND parent.relname = $2
       AND a.attname = $3`,
    [tableName, referencedTableName, columnName],
  );
  return [result.rows, []] as [unknown, unknown[]];
};

const translateAlterTable = (sql: string) => {
  const raw = stripMysqlClauses(sql.trim()).replace(/;$/, "");
  const match = raw.match(/^ALTER\s+TABLE\s+([`"\w.]+)\s+(.+)$/is);
  if (!match) return [translateGenericSql(raw)];
  const tableName = normalizeIdentifier(match[1].split(".").pop() ?? match[1]);
  const action = match[2].trim();

  const addIndex = action.match(/^ADD\s+(UNIQUE\s+)?(?:KEY|INDEX)\s+([`"\w]+)\s*\((.+)\)$/i);
  if (addIndex) {
    const indexName = buildIndexName(tableName, addIndex[2]);
    const unique = addIndex[1] ? "UNIQUE " : "";
    return [`CREATE ${unique}INDEX IF NOT EXISTS ${quoteIdentifier(indexName)} ON ${quoteIdentifier(tableName)} (${replaceBacktickIdentifiers(addIndex[3])})`];
  }

  const dropIndex = action.match(/^DROP\s+INDEX\s+([`"\w]+)$/i);
  if (dropIndex) {
    return [`DROP INDEX IF EXISTS ${quoteIdentifier(dropIndex[1])}`];
  }

  const dropForeignKey = action.match(/^DROP\s+FOREIGN\s+KEY\s+([`"\w]+)$/i);
  if (dropForeignKey) {
    return [`ALTER TABLE ${quoteIdentifier(tableName)} DROP CONSTRAINT IF EXISTS ${quoteIdentifier(dropForeignKey[1])}`];
  }

  if (/^MODIFY\s+/i.test(action)) {
    return [];
  }

  const addColumn = action.match(/^ADD\s+(?:COLUMN\s+)?(.+)$/is);
  if (addColumn && !/^CONSTRAINT\s+/i.test(addColumn[1]) && !/^FOREIGN\s+KEY\s+/i.test(addColumn[1])) {
    return [`ALTER TABLE ${quoteIdentifier(tableName)} ADD COLUMN ${translateColumnDefinition(addColumn[1])}`];
  }

  return [`ALTER TABLE ${quoteIdentifier(tableName)} ${translateGenericSql(action)}`];
};

const translateDateFunctions = (sql: string) =>
  sql
    .replace(/DATE_ADD\s*\(\s*NOW\s*\(\s*\)\s*,\s*INTERVAL\s+(\d+)\s+MINUTE\s*\)/gi, "(NOW() + INTERVAL '$1 minutes')")
    .replace(/DATE_ADD\s*\(\s*NOW\s*\(\s*\)\s*,\s*INTERVAL\s+\?\s+MINUTE\s*\)/gi, "(NOW() + (? * INTERVAL '1 minute'))")
    .replace(/DATE_SUB\s*\(\s*(NOW\s*\(\s*\)|CURRENT_TIMESTAMP)\s*,\s*INTERVAL\s+(\d+)\s+DAY\s*\)/gi, "($1 - INTERVAL '$2 days')")
    .replace(/DATE_SUB\s*\(\s*(NOW\s*\(\s*\)|CURRENT_TIMESTAMP)\s*,\s*INTERVAL\s+\?\s+DAY\s*\)/gi, "($1 - (? * INTERVAL '1 day'))")
    .replace(/DATE_SUB\s*\(\s*(NOW\s*\(\s*\)|CURRENT_TIMESTAMP)\s*,\s*INTERVAL\s+(\d+)\s+HOUR\s*\)/gi, "($1 - INTERVAL '$2 hours')")
    .replace(/DATE_SUB\s*\(\s*(NOW\s*\(\s*\)|CURRENT_TIMESTAMP)\s*,\s*INTERVAL\s+\?\s+HOUR\s*\)/gi, "($1 - (? * INTERVAL '1 hour'))")
    .replace(/NOW\s*\(\s*\)\s*-\s*INTERVAL\s+(\d+)\s+MINUTE/gi, "NOW() - INTERVAL '$1 minutes'")
    .replace(/TIMESTAMPDIFF\s*\(\s*MINUTE\s*,\s*([^)]+?)\s*,\s*NOW\s*\(\s*\)\s*\)/gi, "(EXTRACT(EPOCH FROM (NOW() - $1)) / 60)");

const translateJsonFunctions = (sql: string) =>
  sql
    .replace(
      /JSON_UNQUOTE\s*\(\s*JSON_EXTRACT\s*\(\s*([`"\w.]+)\s*,\s*'\$\.([^']+)'\s*\)\s*\)/gi,
      (_match, column: string, path: string) => `(${replaceBacktickIdentifiers(column)}::jsonb #>> '{${path.replace(/\./g, ",")}}')`,
    )
    .replace(
      /JSON_LENGTH\s*\(\s*([`"\w.]+)\s*\)/gi,
      (_match, column: string) => `COALESCE(jsonb_array_length(NULLIF(${replaceBacktickIdentifiers(column)}, '')::jsonb), 0)`,
    )
    .replace(/\bJSON_OBJECT\s*\(\s*\)/gi, "'{}'")
    .replace(/CAST\s*\(\s*([^)]+?)\s+AS\s+CHAR\s*\)/gi, "CAST($1 AS TEXT)");

const translateGenericSql = (input: string) => {
  let sql = replaceBacktickIdentifiers(input.trim().replace(/;$/, ""));
  sql = translateDateFunctions(sql);
  sql = translateJsonFunctions(sql);
  sql = sql.replace(/\bIFNULL\s*\(/gi, "COALESCE(");
  sql = sql.replace(/\bREGEXP_REPLACE\s*\(/gi, "REGEXP_REPLACE(");
  sql = sql.replace(/\bSUM\s*\(\s*([a-zA-Z_][\w."]*\s*=\s*(?:'[^']+'|\d+))\s*\)/g, "SUM(CASE WHEN $1 THEN 1 ELSE 0 END)");
  sql = sql.replace(
    /\bSUM\s*\(\s*([a-zA-Z_][\w."]*\s+IN\s*\([^)]+\))\s*\)/g,
    "SUM(CASE WHEN $1 THEN 1 ELSE 0 END)",
  );
  return sql;
};

const translateMysqlValuesReferences = (sql: string) =>
  sql.replace(/\bVALUES\s*\(\s*("?[\w]+"?)\s*\)/gi, (_match, column: string) => {
    const normalized = normalizeIdentifier(column);
    return `EXCLUDED.${quoteIdentifier(normalized)}`;
  });

const convertPlaceholders = (sql: string, params: readonly unknown[] = []) => {
  let index = 0;
  let output = "";
  let quote: "'" | "\"" | null = null;
  let dollarTag: string | null = null;
  for (let i = 0; i < sql.length; i += 1) {
    const char = sql[i];
    const previous = i > 0 ? sql[i - 1] : "";

    if (dollarTag) {
      output += char;
      if (sql.slice(i, i + dollarTag.length) === dollarTag) {
        output += sql.slice(i + 1, i + dollarTag.length);
        i += dollarTag.length - 1;
        dollarTag = null;
      }
      continue;
    }

    if (!quote && char === "$") {
      const tagMatch = sql.slice(i).match(/^\$[a-zA-Z_]*\$/);
      if (tagMatch) {
        dollarTag = tagMatch[0];
        output += dollarTag;
        i += dollarTag.length - 1;
        continue;
      }
    }

    if (quote) {
      output += char;
      if (char === quote && previous !== "\\") quote = null;
      continue;
    }

    if (char === "'" || char === "\"") {
      quote = char;
      output += char;
      continue;
    }

    if (char === "?") {
      index += 1;
      const nextSql = sql.slice(i + 1).trimStart();
      const needsNullCheckCast = /^IS\s+(?:NOT\s+)?NULL\b/i.test(nextSql);
      output += `$${index}${needsNullCheckCast ? "::text" : ""}`;
      continue;
    }

    output += char;
  }
  return { sql: output, params };
};

const extractInsertTableName = (sql: string) => {
  const match = sql.match(/^\s*INSERT\s+INTO\s+([`"\w.]+)/i);
  if (!match) return null;
  return normalizeIdentifier(match[1].split(".").pop() ?? match[1]);
};

const loadReturningIdExpression = async (client: PoolClient, tableName: string) => {
  const primaryKey = await client.query(
    `
      SELECT a.attname AS column_name
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
      JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS ord(attnum, ordinality) ON true
      JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ord.attnum
      WHERE n.nspname = current_schema()
        AND t.relname = $1
        AND c.contype = 'p'
      ORDER BY ord.ordinality
      LIMIT 1
    `,
    [tableName],
  );
  const primaryColumn = primaryKey.rows[0]?.column_name;
  if (primaryColumn) {
    return quoteIdentifier(String(primaryColumn));
  }

  const idColumn = await client.query(
    `
      SELECT column_name
      FROM information_schema.columns
      WHERE table_schema = current_schema()
        AND table_name = $1
        AND column_name = 'id'
      LIMIT 1
    `,
    [tableName],
  );
  return idColumn.rows[0]?.column_name ? quoteIdentifier("id") : null;
};

const appendReturningId = async (client: PoolClient, sql: string) => {
  if (!/^\s*INSERT\s+/i.test(sql) || /\bRETURNING\b/i.test(sql)) return sql;
  const tableName = extractInsertTableName(sql);
  if (!tableName) return sql;
  const returningExpression = await loadReturningIdExpression(client, tableName);
  if (!returningExpression) return sql;
  return `${sql} RETURNING ${returningExpression} AS id`;
};

const extractInsertParts = (sql: string) => {
  const match = sql.match(/^\s*INSERT\s+INTO\s+([`"\w.]+)\s*\(([^)]+)\)\s+VALUES\s*/i);
  if (!match) return null;
  return {
    tableName: normalizeIdentifier(match[1].split(".").pop() ?? match[1]),
    columns: splitTopLevel(match[2]).map((column) => normalizeIdentifier(column)),
  };
};

const loadConflictTarget = async (client: PoolClient, tableName: string, insertColumns: string[]) => {
  const result = await client.query(
    `WITH constraint_targets AS (
       SELECT
         c.conname AS name,
         array_agg(a.attname ORDER BY ord.ordinality) AS columns,
         bool_or(c.contype = 'p') AS is_primary
       FROM pg_constraint c
       JOIN pg_class t ON t.oid = c.conrelid
       JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS ord(attnum, ordinality) ON true
       JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ord.attnum
       WHERE t.relname = $1 AND c.contype IN ('p', 'u')
       GROUP BY c.conname
     ),
     index_targets AS (
       SELECT
         i.relname AS name,
         array_agg(a.attname ORDER BY ord.ordinality) AS columns,
         bool_or(ix.indisprimary) AS is_primary
       FROM pg_class t
       JOIN pg_index ix ON ix.indrelid = t.oid
       JOIN pg_class i ON i.oid = ix.indexrelid
       JOIN LATERAL unnest(ix.indkey) WITH ORDINALITY AS ord(attnum, ordinality) ON true
       JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ord.attnum
       WHERE t.relname = $1 AND ix.indisunique AND ix.indpred IS NULL AND ord.attnum > 0
       GROUP BY i.relname
     )
     SELECT DISTINCT ON (columns::text)
       name,
       columns,
       is_primary
     FROM (
       SELECT * FROM constraint_targets
       UNION ALL
       SELECT * FROM index_targets
     ) targets
     ORDER BY columns::text, is_primary ASC, array_length(columns, 1) ASC`,
    [tableName],
  );
  const parseColumns = (value: unknown): string[] => {
    if (Array.isArray(value)) return value.map(String);
    if (typeof value === "string") {
      return value.replace(/^\{|\}$/g, "").split(",").map((item) => item.replace(/^"|"$/g, "")).filter(Boolean);
    }
    return [];
  };
  const insertSet = new Set(insertColumns);
  const candidates = (result.rows as Array<{ columns: unknown; is_primary: boolean }>).map((entry) => ({
    ...entry,
    columns: parseColumns(entry.columns),
  }));
  const candidate = candidates
    .sort((left, right) => Number(left.is_primary) - Number(right.is_primary) || left.columns.length - right.columns.length)
    .find((entry) => entry.columns.every((column) => insertSet.has(column)));
  if (!candidate || candidate.columns.length === 0) {
    return null;
  }
  return `(${candidate.columns.map(quoteIdentifier).join(", ")})`;
};

const isNoopDuplicateUpdate = (updateSql: string) => {
  const assignments = splitTopLevel(updateSql);
  return assignments.length > 0 && assignments.every((assignment) => {
    const match = assignment.match(/^\s*([`"\w]+)\s*=\s*([`"\w]+)\s*$/);
    return match && normalizeIdentifier(match[1]) === normalizeIdentifier(match[2]);
  });
};

const stripLastInsertIdAssignments = (updateSql: string) =>
  splitTopLevel(updateSql)
    .filter((assignment) => !/^\s*[`"\w]+\s*=\s*LAST_INSERT_ID\s*\(/i.test(assignment))
    .join(", ");

const loadTableColumns = async (client: PoolClient, tableName: string) => {
  const result = await client.query(
    `SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = $1`,
    [tableName],
  );
  return new Set(result.rows.map((row) => String(row.column_name).toLowerCase()));
};

const previousNonSpace = (value: string, index: number) => {
  for (let cursor = index - 1; cursor >= 0; cursor -= 1) {
    if (!/\s/.test(value[cursor])) return value[cursor];
  }
  return "";
};

const qualifyTargetColumnsInExpression = (expression: string, columns: Set<string>) => {
  let output = "";
  for (let index = 0; index < expression.length; index += 1) {
    const char = expression[index];
    if (char === "'") {
      let literal = char;
      index += 1;
      for (; index < expression.length; index += 1) {
        literal += expression[index];
        if (expression[index] === "'" && expression[index + 1] === "'") {
          literal += expression[index + 1];
          index += 1;
          continue;
        }
        if (expression[index] === "'") break;
      }
      output += literal;
      continue;
    }
    if (char === "\"") {
      const end = expression.indexOf("\"", index + 1);
      if (end > index) {
        const identifier = expression.slice(index + 1, end);
        const previous = previousNonSpace(output, output.length);
        output += columns.has(identifier.toLowerCase()) && previous !== "." ? `target.${quoteIdentifier(identifier)}` : expression.slice(index, end + 1);
        index = end;
        continue;
      }
    }
    if (/[A-Za-z_]/.test(char)) {
      let end = index + 1;
      while (end < expression.length && /[A-Za-z0-9_]/.test(expression[end])) end += 1;
      const token = expression.slice(index, end);
      const previous = previousNonSpace(output, output.length);
      const next = expression.slice(end).trimStart()[0] ?? "";
      if (columns.has(token.toLowerCase()) && previous !== "." && next !== "(") {
        output += `target.${quoteIdentifier(token)}`;
      } else {
        output += token;
      }
      index = end - 1;
      continue;
    }
    output += char;
  }
  return output;
};

const qualifyUpsertUpdateSql = (updateSql: string, columns: Set<string>, tableName: string) =>
  splitTopLevel(updateSql)
    .map((assignment) => {
      const match = assignment.match(/^(.+?)=(.+)$/s);
      if (!match) return assignment;
      const tableReference = tableName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const expression = match[2]
        .trim()
        .replace(new RegExp(`(?<![\\w"])${tableReference}\\s*\\.\\s*("?\\w+"?)`, "gi"), "target.$1")
        .replace(new RegExp(`${quoteIdentifier(tableName)}\\s*\\.\\s*("?\\w+"?)`, "g"), "target.$1");
      return `${match[1].trim()} = ${qualifyTargetColumnsInExpression(expression, columns)}`;
    })
    .join(", ");

const aliasInsertTarget = (insertSql: string) =>
  insertSql.replace(/^\s*INSERT\s+INTO\s+((?:"[^"]+"|[\w.]+))\s*\(/i, "INSERT INTO $1 AS target (");

const translateUpsert = async (client: PoolClient, sql: string) => {
  const parts = sql.split(/\bON\s+DUPLICATE\s+KEY\s+UPDATE\b/i);
  if (parts.length < 2) return sql;
  const insertSql = translateGenericSql(parts[0].trim());
  const updateSql = translateMysqlValuesReferences(
    translateGenericSql(stripLastInsertIdAssignments(parts.slice(1).join(" ON DUPLICATE KEY UPDATE ").trim())),
  );
  const insertParts = extractInsertParts(insertSql);
  if (!insertParts) return sql;
  const conflictTarget = await loadConflictTarget(client, insertParts.tableName, insertParts.columns);
  if (!conflictTarget) return appendReturningId(client, insertSql);
  const aliasedInsertSql = aliasInsertTarget(insertSql);
  const qualifiedUpdateSql = qualifyUpsertUpdateSql(updateSql, await loadTableColumns(client, insertParts.tableName), insertParts.tableName);
  const returningExpression = await loadReturningIdExpression(client, insertParts.tableName);
  const returningSql = returningExpression ? ` RETURNING ${returningExpression} AS id` : "";
  if (isNoopDuplicateUpdate(updateSql)) {
    return `${aliasedInsertSql} ON CONFLICT ${conflictTarget} DO NOTHING${returningSql ? `${returningSql}, true AS "__inserted"` : ""}`;
  }
  return `${aliasedInsertSql} ON CONFLICT ${conflictTarget} DO UPDATE SET ${qualifiedUpdateSql}${returningSql ? `${returningSql}, (xmax = 0) AS "__inserted"` : ""}`;
};

const translateInsertIgnore = async (client: PoolClient, sql: string) => {
  if (!/^\s*INSERT\s+IGNORE\s+/i.test(sql)) return sql;
  const insertSql = translateGenericSql(sql.replace(/^\s*INSERT\s+IGNORE\s+/i, "INSERT "));
  const insertParts = extractInsertParts(insertSql);
  if (!insertParts) return `${insertSql} ON CONFLICT DO NOTHING`;
  const conflictTarget = await loadConflictTarget(client, insertParts.tableName, insertParts.columns);
  const returningExpression = await loadReturningIdExpression(client, insertParts.tableName);
  const returningSql = returningExpression ? ` RETURNING ${returningExpression} AS id` : "";
  return `${insertSql} ON CONFLICT ${conflictTarget ?? ""} DO NOTHING${returningSql}`.replace(/\s+ON CONFLICT\s+DO/, " ON CONFLICT DO");
};

const translateLimitedMutation = (sql: string) => {
  const deleteLeftJoinMatch = sql.match(
    /^\s*DELETE\s+([`"\w]+)\s+FROM\s+([`"\w.]+)\s+\1\s+LEFT\s+JOIN\s+([`"\w.]+)\s+([`"\w]+)\s+ON\s+(.+?)\s+WHERE\s+\4\.id\s+IS\s+NULL\s+AND\s+(.+)$/is,
  );
  if (deleteLeftJoinMatch) {
    const alias = quoteIdentifier(normalizeIdentifier(deleteLeftJoinMatch[1]));
    const table = replaceBacktickIdentifiers(deleteLeftJoinMatch[2]);
    const joinTable = replaceBacktickIdentifiers(deleteLeftJoinMatch[3]);
    const joinAlias = quoteIdentifier(normalizeIdentifier(deleteLeftJoinMatch[4]));
    const joinCondition = deleteLeftJoinMatch[5];
    const where = deleteLeftJoinMatch[6];
    return `DELETE FROM ${table} AS ${alias} WHERE NOT EXISTS (SELECT 1 FROM ${joinTable} AS ${joinAlias} WHERE ${joinCondition}) AND ${where}`;
  }
  const deleteJoinMatch = sql.match(/^\s*DELETE\s+([`"\w]+)\s+FROM\s+([`"\w.]+)\s+\1\s+WHERE\s+(.+)$/is);
  if (deleteJoinMatch) {
    const alias = quoteIdentifier(normalizeIdentifier(deleteJoinMatch[1]));
    const table = replaceBacktickIdentifiers(deleteJoinMatch[2]);
    const where = deleteJoinMatch[3];
    return `DELETE FROM ${table} AS ${alias} WHERE ${where}`;
  }
  const deleteMatch = sql.match(/^\s*DELETE\s+FROM\s+([`"\w.]+)\s+WHERE\s+(.+?)\s+LIMIT\s+(\$\d+|\d+)\s*$/is);
  if (deleteMatch) {
    const table = replaceBacktickIdentifiers(deleteMatch[1]);
    const where = deleteMatch[2];
    const limit = deleteMatch[3];
    return `DELETE FROM ${table} WHERE ctid IN (SELECT ctid FROM ${table} WHERE ${where} LIMIT ${limit})`;
  }
  const updateMatch = sql.match(/^\s*UPDATE\s+([`"\w.]+)\s+SET\s+(.+?)\s+WHERE\s+(.+?)\s+LIMIT\s+(\$\d+|\d+)\s*$/is);
  if (updateMatch) {
    const table = replaceBacktickIdentifiers(updateMatch[1]);
    const setClause = updateMatch[2];
    const where = updateMatch[3];
    const limit = updateMatch[4];
    return `UPDATE ${table} SET ${setClause} WHERE ctid IN (SELECT ctid FROM ${table} WHERE ${where} LIMIT ${limit})`;
  }
  return sql;
};

const normalizeParams = (params?: QueryParams) => Array.isArray(params) ? [...params] : [];

const runTranslatedSql = async <T>(
  client: PoolClient,
  sql: string,
  params?: QueryParams,
): Promise<[T, unknown[]]> => {
  const normalizedParams = normalizeParams(params);
  const trimmed = sql.trim();

  const showColumns = await translateShowColumns(client, trimmed, normalizedParams);
  if (showColumns) return showColumns as [T, unknown[]];

  const showIndex = await translateShowIndex(client, trimmed, normalizedParams);
  if (showIndex) return showIndex as [T, unknown[]];

  const referentialConstraints = await translateReferentialConstraints(client, trimmed);
  if (referentialConstraints) return referentialConstraints as [T, unknown[]];

  const statements = /^\s*CREATE\s+TABLE\s+/i.test(trimmed)
    ? (() => {
        const translated = translateCreateTable(trimmed);
        return [translated.mainSql, ...translated.afterSql];
      })()
    : /^\s*ALTER\s+TABLE\s+/i.test(trimmed)
      ? translateAlterTable(trimmed)
      : [trimmed];

  let lastResult: QueryResult | null = null;
  for (const statement of statements) {
    if (!statement.trim()) continue;
    let translated = translateGenericSql(statement);
    if (/\bON\s+DUPLICATE\s+KEY\s+UPDATE\b/i.test(translated)) {
      translated = await translateUpsert(client, translated);
    } else if (/^\s*INSERT\s+IGNORE\s+/i.test(translated)) {
      translated = await translateInsertIgnore(client, translated);
    } else {
      translated = await appendReturningId(client, translated);
    }
    const converted = convertPlaceholders(translateLimitedMutation(translated), normalizedParams);
    lastResult = await client.query(converted.sql, converted.params as unknown[]);
  }

  if (!lastResult) {
    return [{ affectedRows: 0, changedRows: 0, insertId: 0, warningStatus: 0, rowCount: 0 } as T, []];
  }

  if (lastResult.command === "SELECT" || lastResult.command === "SHOW") {
    return [lastResult.rows as T, []];
  }

  const firstRow = lastResult.rows[0];
  const firstId = firstRow?.id;
  const affectedRows = firstRow?.__inserted === false ? 2 : (lastResult.rowCount ?? 0);
  const header: MysqlCompatHeader = {
    affectedRows,
    changedRows: affectedRows,
    insertId: typeof firstId === "number" ? firstId : Number(firstId || 0),
    warningStatus: 0,
    rowCount: lastResult.rowCount ?? 0,
  };
  return [header as T, []];
};

class PgCompatConnection implements DatabaseConnection {
  constructor(private readonly client: PoolClient) {}

  query<T = unknown>(sql: string, params?: QueryParams) {
    return runTranslatedSql<T>(this.client, sql, params);
  }

  execute<T = unknown>(sql: string, params?: QueryParams) {
    return this.query<T>(sql, params);
  }

  async beginTransaction() {
    await this.client.query("BEGIN");
  }

  async commit() {
    await this.client.query("COMMIT");
  }

  async rollback() {
    await this.client.query("ROLLBACK");
  }

  release() {
    this.client.release();
  }
}

class PgCompatPool implements DatabasePool {
  constructor(private readonly pool: PgPool) {}

  async query<T = unknown>(sql: string, params?: QueryParams) {
    const client = await this.pool.connect();
    try {
      return await runTranslatedSql<T>(client, sql, params);
    } finally {
      client.release();
    }
  }

  execute<T = unknown>(sql: string, params?: QueryParams) {
    return this.query<T>(sql, params);
  }

  async getConnection() {
    const client = await this.pool.connect();
    return new PgCompatConnection(client);
  }

  async end() {
    await this.pool.end();
  }
}

export const createPostgresCompatPool = () => {
  const connectionString = process.env.DATABASE_URL?.trim();
  const pool = new PgPool({
    connectionString: connectionString || undefined,
    host: connectionString ? undefined : process.env.DATABASE_HOST ?? "127.0.0.1",
    port: connectionString ? undefined : Number(process.env.DATABASE_PORT ?? 7778),
    user: connectionString ? undefined : process.env.DATABASE_USER ?? "botadmin",
    password: connectionString ? undefined : process.env.DATABASE_PASSWORD ?? "",
    database: connectionString ? undefined : process.env.DATABASE_NAME ?? "botadmin",
    max: Number(process.env.DATABASE_CONNECTION_LIMIT ?? 20),
    idleTimeoutMillis: Number(process.env.DATABASE_IDLE_TIMEOUT ?? 300_000),
    connectionTimeoutMillis: Number(process.env.DATABASE_CONNECT_TIMEOUT ?? 5_000),
    keepAlive: true,
  });
  return new PgCompatPool(pool);
};
