export type BotMenuConfig = {
  id: number;
  userId: number;
  menuText: string;
  menuFooterText: string | null;
  menuButtonBuyText: string;
  menuButtonAddBalanceText: string;
  menuButtonSupportText: string;
  menuButtonProfileText: string;
  categoryListHeaderText: string;
  categoryListBodyText: string;
  categoryListFooterText: string;
  categoryListFooterMoreText: string;
  categoryListButtonText: string;
  categoryListSectionTitle: string;
  categoryListNextTitle: string;
  categoryListNextDescription: string;
  categoryListEmptyText: string;
  categoryDetailBodyText: string;
  categoryDetailFooterText: string;
  categoryDetailButtonText: string;
  categoryDetailFileCaption: string | null;
  addBalanceReplyText: string;
  supportReplyText: string;
  profileMenuBodyText: string;
  profileMenuFooterText: string | null;
  profileButtonPurchasesText: string;
  profileButtonSupportText: string;
  profileButtonBackText: string;
  profilePurchasesHeaderText: string;
  profilePurchasesBodyText: string;
  profilePurchasesFooterText: string;
  profilePurchasesEmptyText: string;
  profilePurchasesButtonText: string;
  profileSupportReasonBodyText: string;
  profileSupportReasonFooterText: string | null;
  profileSupportReasonPurchaseText: string;
  profileSupportReasonPaymentText: string;
  profileSupportReasonOtherText: string;
  variables: string[];
  imagePath: string | null;
  updatedAt: string;
};
