import type { BotGroupMenuTexts } from "../types/bot-groups";

export const DEFAULT_MENU_TEXTS: BotGroupMenuTexts = {
  main: [
    "╭━━━ 乂 𝑰 𝑵 𝑭 𝑶 乂 ━━━╮",
    "┃ 👤 𝑼𝒔𝒖á𝒓𝒊𝒐: {usuario}",
    "┃ 📲 𝑵ú𝒎𝒆𝒓𝒐: {numerousuario}",
    "┃ 🤖 𝑩𝒐𝒕: {nomebot}",
    "┃ 📱 𝑵º 𝒅𝒐 𝒃𝒐𝒕: {numerobot}",
    "╰━━━━━━━━━━━━━╯",
    "",
    "╭━━━ 乂 𝑩𝑶𝑻𝑨𝑫𝑴𝑰𝑵 乂 ━━━╮",
    "┃ 💜 𝑶 𝒎𝒆𝒍𝒉𝒐𝒓 𝒃𝒐𝒕 𝒑𝒂𝒓𝒂 𝒎𝒐𝒅𝒆𝒓𝒂çã𝒐 𝒆 𝒊𝒏𝒕𝒆𝒓𝒂çã𝒐 𝒆𝒎 𝒈𝒓𝒖𝒑𝒐𝒔.",
    "┃ ✨ 𝑬𝒔𝒄𝒐𝒍𝒉𝒂 𝒖𝒎𝒂 𝒍𝒊𝒔𝒕𝒂 𝒂𝒃𝒂𝒊𝒙𝒐.",
    "╰━━━━━━━━━━━━━╯",
  ],
  admin: [
    "𝑴𝑬𝑵𝑼 𝑨𝑫𝑴",
    "╭━━━ 乂 🤖 𝑰𝑨 𝑫𝑶 𝑮𝑹𝑼𝑷𝑶 乂 ━━━╮",
    "┃ 🤖 {prefix}botinterage · {prefix}vozbotinterage",
    "┃ 🧠 {prefix}keygroq · {prefix}promptbot",
    "┃ 🛡️ {prefix}moderacaocomia · {prefix}lerimagem",
    "┣━━ 乂 👋 𝑩𝑶𝑨𝑺-𝑽𝑰𝑵𝑫𝑨𝑺 乂 ━━┫",
    "┃ 👋 {prefix}bemvindo",
    "┃ 🖼️ {prefix}fundobemvindo",
    "┃ ✍️ {prefix}legendabemvindo",
    "┣━━ 乂 🛡️ 𝑷𝑹𝑶𝑻𝑬ÇÕ𝑬𝑺 乂 ━━┫",
    "┃ 🔗 {prefix}antilink · {prefix}antilinkgp",
    "┃ 🚫 {prefix}banextremo · {prefix}antipalavras · {prefix}soadm",
    "┃ 📵 {prefix}antisticker · antimage · antvideo · antaudio",
    "┃ 📄 {prefix}antdoc · antvcard · antinsfwimagem · proibirnsfw",
    "┣━━ 乂 🚫 𝑳𝑰𝑺𝑻𝑨𝑺 𝑬 𝑷𝑬𝑹𝑴𝑰𝑺𝑺Õ𝑬𝑺 乂 ━━┫",
    "┃ ✅ {prefix}permitirlink · {prefix}removerlink",
    "┃ 🚷 {prefix}addblacklist · {prefix}rmblacklist",
    "┃ 🌎 {prefix}rmgringos · {prefix}removerinativos 5d",
    "┃ 🧊 {prefix}removerinativosauto 30d · {prefix}removerinativosauto off",
    "┣━━ 乂 👮 𝑴𝑶𝑫𝑬𝑹𝑨ÇÃ𝑶 乂 ━━┫",
    "┃ 👮 {prefix}ban · {prefix}mutar · {prefix}desmutar",
    "┃ ⭐ {prefix}promover · {prefix}rebaixar",
    "┃ 🗑️ {prefix}apagar · {prefix}limitemute",
    "┣━━ 乂 💬 𝑴𝑬𝑵𝑺𝑨𝑮𝑬𝑵𝑺 乂 ━━┫",
    "┃ 💬 {prefix}autoresposta · addautorepo · rmautorepo",
    "┃ 📋 {prefix}listaautorepo · {prefix}addregras · {prefix}addtabela",
    "┃ 🎨 {prefix}fundomenu · {prefix}autosticker · {prefix}autodownloader",
    "┣━━ 乂 ⏱️ 𝑹𝑶𝑻𝑰𝑵𝑨𝑺 乂 ━━┫",
    "┃ ⏱️ {prefix}addhorapg · {prefix}fecharauto · {prefix}abrirauto",
    "┃ 🕒 {prefix}horariotz · {prefix}fechargrupo · {prefix}abrirgrupo",
    "┃ 🔗 {prefix}linkgp · {prefix}renovarplano",
    "┃ 📣 {prefix}marcar · {prefix}mencionar · {prefix}resetarranking",
    "╰━━━━━━━━━━━━━━━━━━━━╯",
  ],
  comandos: [
    "𝑴𝑬𝑵𝑼 𝑫𝑬 𝑪𝑶𝑴𝑨𝑵𝑫𝑶𝑺",
    "╭━━━ 乂 💎 𝑷𝑳𝑨𝑵𝑶 𝑬 𝑮𝑹𝑼𝑷𝑶 乂 ━━━╮",
    "┃ ⏰ {prefix}vencimento — 𝒗𝒂𝒍𝒊𝒅𝒂𝒅𝒆",
    "┃ 📜 {prefix}regras · {prefix}tabela",
    "┃ ⏱️ {prefix}horapg · {prefix}ranking · {prefix}meuranking",
    "┃ 👑 {prefix}dono · {prefix}painel",
    "┣━━ 乂 📥 𝑫𝑶𝑾𝑵𝑳𝑶𝑨𝑫𝑺 乂 ━━┫",
    "┃ ▶️ {prefix}play <nome> — 𝒂ú𝒅𝒊𝒐/𝒗í𝒅𝒆𝒐",
    "┃ 🔎 {prefix}yt <termo> — 𝒍𝒊𝒔𝒕𝒂 𝒄𝒐𝒎 𝒑𝒓é𝒗𝒊𝒂",
    "┃ 🎵 {prefix}ytmp3 · 🎬 {prefix}ytmp4",
    "┃ 📱 {prefix}tiktok · {prefix}kwai · {prefix}insta",
    "┃ 📌 {prefix}savepin · {prefix}spotify · {prefix}mediafire",
    "┣━━ 乂 🎨 𝑭𝑰𝑮𝑼𝑹𝑰𝑵𝑯𝑨𝑺 𝑬 𝑽𝑶𝒁 乂 ━━┫",
    "┃ 🖼️ {prefix}attp · {prefix}attp2 · {prefix}attp3",
    "┃ ✍️ {prefix}gerarfrase · {prefix}frase · {prefix}frase2 · {prefix}frase3",
    "┃ 🎙️ {prefix}tts · {prefix}videotts · {prefix}legendaaudio",
    "┃ 🔗 {prefix}tourl · {prefix}listatts · {prefix}infovideotts",
    "╰━━━━━━━━━━━━━━━━━━━━╯",
  ],
  outros: [
    "𝑶𝑼𝑻𝑹𝑨𝑺 𝑰𝑵𝑭𝑶𝑹𝑴𝑨ÇÕ𝑬𝑺",
    "╭━━━ 乂 𝑨𝑻𝑨𝑳𝑯𝑶𝑺 乂 ━━━╮",
    "┃ 📜 {prefix}regras — 𝒎𝒂𝒕𝒆𝒓𝒊𝒂𝒍 𝒇𝒊𝒙𝒐",
    "┃ 📋 {prefix}tabela — 𝒄𝒐𝒎𝒖𝒏𝒊𝒄𝒂𝒅𝒐𝒔",
    "┃ 🧭 {prefix}comandos — 𝒄𝒐𝒎𝒂𝒏𝒅𝒐𝒔 𝒈𝒆𝒓𝒂𝒊𝒔",
    "┃ 🛡️ {prefix}menuadm — 𝒄𝒐𝒎𝒂𝒏𝒅𝒐𝒔 𝒅𝒆 𝒂𝒅𝒎𝒊𝒏",
    "╰━━━━━━━━━━━━━━━━━━━━╯",
  ],
  downloads: [
    "𝑴𝑬𝑵𝑼 𝑫𝑬 𝑫𝑶𝑾𝑵𝑳𝑶𝑨𝑫𝑺",
    "╭━━━ 乂 𝑴Í𝑫𝑰𝑨𝑺 乂 ━━━╮",
    "┃ ▶️ {prefix}play <música> — 𝒀𝒐𝒖𝑻𝒖𝒃𝒆 𝒂ú𝒅𝒊𝒐/𝒗í𝒅𝒆𝒐",
    "┃ 🔎 {prefix}yt <termo> — 𝒑𝒓é𝒗𝒊𝒂𝒔 𝒄𝒐𝒎 𝒄𝒂𝒑𝒂",
    "┃ 🎵 {prefix}ytmp3 <link/termo> — 𝒔ó 𝒂ú𝒅𝒊𝒐",
    "┃ 🎬 {prefix}ytmp4 <link/termo> — 𝒗í𝒅𝒆𝒐 𝒄𝒐𝒎𝒑𝒍𝒆𝒕𝒐",
    "┃ 📱 {prefix}tiktok · {prefix}kwai · {prefix}insta",
    "┃ ✂️ {prefix}edit <link/vídeo> — 𝒄𝒐𝒓𝒕𝒆 𝒑𝒂𝒓𝒂 𝑺𝒉𝒐𝒓𝒕𝒔",
    "┃ 📌 {prefix}savepin · {prefix}spotify · {prefix}mediafire",
    "╰━━━━━━━━━━━━━━━━━━━━╯",
  ],
  ativacoes: [
    "𝑴𝑬𝑵𝑼 𝑫𝑬 𝑨𝑻𝑰𝑽𝑨ÇÕ𝑬𝑺",
    "╭━━━ 乂 𝑳𝑰𝑮𝑨 / 𝑫𝑬𝑺𝑳𝑰𝑮𝑨 乂 ━━━╮",
    "┃ 🛡️ {prefix}antilink / {prefix}antilinkgp",
    "┃ 🚫 {prefix}banextremo",
    "┃ 🤖 {prefix}botinterage",
    "┃ 🎙️ {prefix}vozbotinterage",
    "┃ 🖼️ {prefix}autosticker",
    "┃ 📥 {prefix}autodownloader",
    "┃ 💬 {prefix}autoresposta · addautorepo · rmautorepo",
    "┃ 👋 {prefix}bemvindo",
    "┃ 🎨 {prefix}fundomenu · {prefix}fundobemvindo",
    "┃ 🏆 {prefix}resetarranking",
    "┃ 🔐 {prefix}soadm",
    "╰━━━━━━━━━━━━━━━━━━━━╯",
  ],
  jogos: [
    "𝑨𝑺𝑺𝑰𝑺𝑻𝑬𝑵𝑻𝑬 𝑷𝑹𝑶𝑭𝑰𝑺𝑺𝑰𝑶𝑵𝑨𝑳",
    "╭━━━ 乂 𝑩𝑶𝑻𝑨𝑫𝑴𝑰𝑵 乂 ━━━╮",
    "┃ 💼 𝑴𝒐𝒅𝒆𝒓𝒂çã𝒐 𝒆 𝒊𝒏𝒕𝒆𝒓𝒂çã𝒐 𝒑𝒂𝒓𝒂 𝒈𝒓𝒖𝒑𝒐𝒔.",
    "┃ 🧭 𝑼𝒔𝒆 {prefix}menu 𝒑𝒂𝒓𝒂 𝒗𝒆𝒓 𝒂𝒔 𝒐𝒑çõ𝒆𝒔.",
    "╰━━━━━━━━━━━━━━━━━━━━╯",
  ],
};

export const MENU_TEXT_VARIABLES = [
  {
    token: "{usuario}",
    description: "Nome do contato que chamou o menu (ou “Usuário” quando o nome não é conhecido).",
    example: "Maria Souza",
  },
  {
    token: "{numerousuario}",
    description: "Número do contato que chamou o menu.",
    example: "5511999999999",
  },
  {
    token: "{bot}",
    description: "Identificação curta da instância (ID remoto ou nome interno).",
    example: "laizza-01",
  },
  {
    token: "{nomebot}",
    description: "Nome configurado da instância ou apelido do bot mostrado aos clientes.",
    example: "Assistente VIP",
  },
  {
    token: "{numerobot}",
    description: "Número completo do bot/instância que respondeu ao comando.",
    example: "5511999999999",
  },
  {
    token: "{vencimento}",
    description: "Origem da cobertura + data de validade resumida.",
    example: "Plano Premium · 12/11/2024",
  },
  {
    token: "{origem}",
    description: "Origem da cobertura atual (plano principal ou add-on).",
    example: "Plano Premium",
  },
  {
    token: "{coverageSource}",
    description: "Versão em inglês do campo {origem}, útil para integrações legadas.",
    example: "Plano Premium",
  },
  {
    token: "{dataVencimento}",
    description: "Data de validade pura (ISO) quando disponível.",
    example: "2024-11-12",
  },
  {
    token: "{prefix}",
    description: "Prefixo principal ativo naquele momento (ex.: /, !, .).",
    example: "/",
  },
  {
    token: "{prefixo}",
    description: "Alias em português do mesmo prefixo exibido por {prefix}.",
    example: "/",
  },
  {
    token: "{grupo}",
    description: "ID completo ou nome do grupo conforme disponível.",
    example: "120363148765432109@g.us",
  },
  {
    token: "{nomegrupo}",
    description: "Nome amigável do grupo (fallback para o ID se não houver).",
    example: "Clientes Prime 01",
  },
] as const;
