export const DEFAULT_COMMAND_ALIASES: Record<string, string[]> = {
  menu: ["menu", "m"],
  comandos: ["comandos"],
  prefix: ["prefix", "prefixo"],
  id: ["id"],
  antilink: ["antilink"],
  antilinkgp: ["antilinkgp"],
  banextremo: ["banextremo"],
  bangringos: ["bangringos"],
  antipalavras: ["antipalavras"],
  antinsfwimagem: ["antinsfwimagem", "antinsfw"],
  proibirnsfw: ["proibirnsfw"],
  soadm: ["soadm"],
  autoresposta: ["autoresposta"],
  addautorepo: ["addautorepo", "addautoresposta"],
  rmautorepo: ["rmautorepo", "removeautorepo"],
  listaautorepo: ["listaautorepo", "listautorepo"],
  frase: ["frase"],
  frase2: ["frase2"],
  frase3: ["frase3"],
  frase4: ["frase4"],
  gerarfrase: ["gerarfrase"],
  frasenovideo: ["frasenovideo", "frasevideo"],
  frasenovideo2: ["frasenovideo2", "frasevideo2"],
  tts: ["tts"],
  videotts: ["videotts"],
  legendaaudio: ["legendaaudio", "audiovideo", "audionovideo", "videodoaudio", "vozvideo"],
  infovideotts: ["infovideotts"],
  listatts: ["listatts", "listtts", "listartts", "vozes", "vozestts"],
  clonarvoz: ["clonarvoz"],
  rmtts: ["rmtts", "removertts", "apagartts"],
  addregras: ["addregras"],
  regras: ["regras"],
  addtabela: ["addtabela"],
  tabela: ["tabela"],
  botinterage: ["botinterage"],
  vozbotinterage: ["vozbotinterage"],
  lerimagem: ["lerimagem"],
  autosticker: ["autosticker"],
  autodownloader: ["autodownloader"],
  bemvindo: ["bemvindo"],
  despedida: ["despedida", "saida", "mensagemsaida"],
  addblacklist: ["addblacklist", "addbl", "blacklistadd"],
  rmblacklist: ["rmblacklist", "delblacklist", "removeblacklist", "rmbl"],
  rmgringos: ["rmgringos", "limpargringos", "removergringos"],
  antisticker: ["antisticker", "antifigurinha"],
  antimage: ["antimage", "antiimagem"],
  antvideo: ["antvideo", "antivideo"],
  antaudio: ["antaudio", "antiaudio"],
  antdoc: ["antdoc", "antidoc", "antidocumento"],
  antvcard: ["antvcard", "anticontato"],
  ranking: ["ranking"],
  horapg: ["horapg"],
  addhorapg: ["addhorapg"],
  fecharauto: ["fecharauto"],
  abrirauto: ["abrirauto"],
  horariotz: ["horariotz", "horariozona"],
  yt: ["yt", "ytsearch"],
  ytmp3: ["ytmp3", "ytplay", "playu", "song"],
  ytmp4: ["ytmp4"],
  tomp3: ["tomp3"],
  play: ["play", "musica", "video"],
  tiktok: ["tiktok"],
  douyin: ["douyin"],
  edit: ["edit", "editarvideo", "videoviral", "shortedit"],
  kwai: ["kwai"],
  shopee: ["shopee"],
  mercadolivre: ["mercadolivre", "mlivre", "meli", "ml"],
  savepin: ["savepin", "pinterest", "pin"],
  spotify: ["spotify"],
  spotifydl: ["spotifydl"],
  soundcloud: ["soundcloud"],
  bandcamp: ["bandcamp"],
  mixcloud: ["mixcloud"],
  twitterspaces: ["twitterspaces", "spaces"],
  twitch: ["twitch"],
  rumble: ["rumble"],
  odysee: ["odysee", "lbry"],
  dailymotion: ["dailymotion", "dm"],
  facebook: ["facebook", "fbvideo", "fbwatch"],
  mediafire: ["mediafire"],
  insta: ["insta", "instagram"],
  attp: ["attp"],
  attp2: ["attp2"],
  attp3: ["attp3"],
  sticker: ["sticker", "s"],
  sticker2: ["sticker2", "s2"],
  fig: ["fig", "gif", "figurinhas", "stickers"],
  fig2: ["fig2", "figpack", "stickerpack"],
  rename: ["rename", "renomear"],
  mute: ["mute", "mutar", "silenciar"],
  unmute: ["unmute", "desmutar", "ativar"],
  ban: ["ban", "banir"],
  adv: ["adv", "advertir", "advertencia", "advertência"],
  apagar: ["apagar", "delmsg"],
  permitirlink: ["permitirlink", "addlink", "whitelistadd"],
  removerlink: ["removerlink", "removelink", "whitelistdel"],
  keygroq: ["keygroq", "definirkey"],
  promptbot: ["promptbot", "setprompt"],
  fundomenu: ["fundomenu"],
  fundobemvindo: ["fundobemvindo"],
  legendabemvindo: ["legendabemvindo"],
  marcar: ["marcar", "tagall"],
  mencionar: ["mencionar", "ghosttag", "totag"],
  linkgp: ["linkgp", "linkgrupo"],
  menuadm: ["menuadm", "menuadmin"],
  vencimento: ["vencimento", "validade"],
  idiomas: ["idiomas", "idioma"],
  antiafk: ["antiafk", "antighost", "antiinatividade", "anti-inatividade", "antiinativos"],
  removerinativos: ["removerinativos", "limparinativos"],
  removerinativosauto: ["removerinativosauto", "limparinativosauto"],
  meuranking: ["meuranking", "meurank"],
  resetarranking: ["resetarranking", "zerarranking", "resetaranking"],
  coins: ["coins", "botcoins", "moedas", "botcoin"],
  coinsrank: ["coinsrank", "rankcoins", "rankingcoins"],
  menubotcoins: ["menubotcoins", "menucoins", "menubc", "botcoinsmenu"],
  bcshop: ["bcshop", "lojabc", "lojabotcoins"],
  comprarbc: ["comprarbc", "comprardefesa", "compraritem"],
  defesabc: ["defesabc", "defesabotcoins", "minhasdefesas"],
  roubarbc: ["roubarbc", "roubarbotcoins", "roubarcoins"],
  comprarcoins: ["comprarcoins", "comprarbotcoins", "comprarmoedas", "recarregarcoins"],
  sisreg: ["sisreg"],
  rmsisreg: ["rmsisreg"],
  revelar: ["revelar", "r"],
};
