import 'dart:math' as math;

import 'package:flutter/material.dart';

import '../../core/wa_theme.dart';

const List<String> emojiFontFallback = [
  'NotoColorEmoji',
  'Apple Color Emoji',
  'Segoe UI Emoji',
  'Noto Emoji',
];

TextStyle emojiTextStyle(double size) {
  return TextStyle(fontSize: size, fontFamilyFallback: emojiFontFallback);
}

/// Catálogo de emojis estilo WhatsApp (composer + reações).
class EmojiCatalog {
  const EmojiCatalog._();

  /// Barra oficial de reações rápidas do WhatsApp (6 + “mais”).
  static const List<String> quickReactions = [
    '👍',
    '❤️',
    '😂',
    '😮',
    '😢',
    '🙏',
  ];

  /// Atalhos extras no seletor completo.
  static const List<String> extraQuickReactions = [
    '👏',
    '🔥',
    '🎉',
    '💯',
    '😍',
    '🥰',
    '😊',
    '😁',
    '🤔',
    '👀',
    '🙌',
    '💪',
    '✅',
    '❌',
  ];

  static const List<EmojiCategory> categories = [
    EmojiCategory(
      id: 'smileys',
      label: 'Rostos',
      icon: '😀',
      emojis: [
        '😀',
        '😃',
        '😄',
        '😁',
        '😆',
        '😅',
        '🤣',
        '😂',
        '🙂',
        '🙃',
        '😉',
        '😊',
        '😇',
        '🥰',
        '😍',
        '🤩',
        '😘',
        '😗',
        '😚',
        '😙',
        '🥲',
        '😋',
        '😛',
        '😜',
        '🤪',
        '😝',
        '🤑',
        '🤗',
        '🤭',
        '🤫',
        '🤔',
        '🤐',
        '🤨',
        '😐',
        '😑',
        '😶',
        '😏',
        '😒',
        '🙄',
        '😬',
        '😮‍💨',
        '🤥',
        '😌',
        '😔',
        '😪',
        '🤤',
        '😴',
        '😷',
        '🤒',
        '🤕',
        '🤢',
        '🤮',
        '🤧',
        '🥵',
        '🥶',
        '🥴',
        '😵',
        '🤯',
        '🤠',
        '🥳',
        '🥸',
        '😎',
        '🤓',
        '🧐',
        '😕',
        '😟',
        '🙁',
        '☹️',
        '😮',
        '😯',
        '😲',
        '😳',
        '🥺',
        '😦',
        '😧',
        '😨',
        '😰',
        '😥',
        '😢',
        '😭',
        '😱',
        '😖',
        '😣',
        '😞',
        '😓',
        '😩',
        '😫',
        '🥱',
        '😤',
        '😡',
        '😠',
        '🤬',
        '😈',
        '👿',
        '💀',
        '☠️',
        '💩',
        '🤡',
        '👹',
        '👺',
        '👻',
        '👽',
        '👾',
        '🤖',
        '😺',
        '😸',
        '😹',
        '😻',
        '😼',
        '😽',
        '🙀',
        '😿',
        '😾',
      ],
    ),
    EmojiCategory(
      id: 'gestures',
      label: 'Gestos',
      icon: '👋',
      emojis: [
        '👋',
        '🤚',
        '🖐️',
        '✋',
        '🖖',
        '👌',
        '🤌',
        '🤏',
        '✌️',
        '🤞',
        '🤟',
        '🤘',
        '🤙',
        '👈',
        '👉',
        '👆',
        '🖕',
        '👇',
        '☝️',
        '👍',
        '👎',
        '✊',
        '👊',
        '🤛',
        '🤜',
        '👏',
        '🙌',
        '👐',
        '🤲',
        '🤝',
        '🙏',
        '✍️',
        '💅',
        '🤳',
        '💪',
        '🦾',
        '🦿',
        '🦵',
        '🦶',
        '👂',
        '🦻',
        '👃',
        '🧠',
        '🫀',
        '🫁',
        '🦷',
        '🦴',
        '👀',
        '👁️',
        '👅',
        '👄',
        '💋',
        '🩸',
      ],
    ),
    EmojiCategory(
      id: 'people',
      label: 'Pessoas',
      icon: '👤',
      emojis: [
        '👶',
        '🧒',
        '👦',
        '👧',
        '🧑',
        '👱',
        '👨',
        '🧔',
        '👩',
        '🧓',
        '👴',
        '👵',
        '🙍',
        '🙎',
        '🙅',
        '🙆',
        '💁',
        '🙋',
        '🧏',
        '🙇',
        '🤦',
        '🤷',
        '👮',
        '🕵️',
        '💂',
        '🥷',
        '👷',
        '🤴',
        '👸',
        '👳',
        '👲',
        '🧕',
        '🤵',
        '👰',
        '🤰',
        '🤱',
        '👼',
        '🎅',
        '🤶',
        '🦸',
        '🦹',
        '🧙',
        '🧚',
        '🧛',
        '🧜',
        '🧝',
        '🧞',
        '🧟',
        '💆',
        '💇',
        '🚶',
        '🧍',
        '🧎',
        '🏃',
        '💃',
        '🕺',
        '🕴️',
        '👯',
        '🧖',
        '🧗',
        '🤺',
        '🏇',
        '⛷️',
        '🏂',
        '🏌️',
        '🏄',
        '🚣',
        '🏊',
        '⛹️',
        '🏋️',
        '🚴',
        '🚵',
        '🤸',
        '🤼',
        '🤽',
        '🤾',
        '🤹',
        '🧘',
        '🛀',
        '🛌',
        '👭',
        '👫',
        '👬',
        '💏',
        '💑',
        '👪',
      ],
    ),
    EmojiCategory(
      id: 'animals',
      label: 'Animais',
      icon: '🐶',
      emojis: [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐻‍❄️',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐽',
        '🐸',
        '🐵',
        '🙈',
        '🙉',
        '🙊',
        '🐒',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🐣',
        '🐥',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐗',
        '🐴',
        '🦄',
        '🐝',
        '🪱',
        '🐛',
        '🦋',
        '🐌',
        '🐞',
        '🐜',
        '🪰',
        '🪲',
        '🪳',
        '🦟',
        '🦗',
        '🕷️',
        '🕸️',
        '🦂',
        '🐢',
        '🐍',
        '🦎',
        '🦖',
        '🦕',
        '🐙',
        '🦑',
        '🦐',
        '🦞',
        '🦀',
        '🐡',
        '🐠',
        '🐟',
        '🐬',
        '🐳',
        '🐋',
        '🦈',
        '🐊',
        '🐅',
        '🐆',
        '🦓',
        '🦍',
        '🦧',
        '🦣',
        '🐘',
        '🦛',
        '🦏',
        '🐪',
        '🐫',
        '🦒',
        '🦘',
        '🦬',
        '🐃',
        '🐂',
        '🐄',
        '🐎',
        '🐖',
        '🐏',
        '🐑',
        '🦙',
        '🐐',
        '🦌',
        '🐕',
        '🐩',
        '🦮',
        '🐕‍🦺',
        '🐈',
        '🐈‍⬛',
        '🪶',
        '🐓',
        '🦃',
        '🦤',
        '🦚',
        '🦜',
        '🦢',
        '🦩',
        '🕊️',
        '🐇',
        '🦝',
        '🦨',
        '🦡',
        '🦫',
        '🦦',
        '🦥',
        '🐁',
        '🐀',
        '🐿️',
        '🦔',
      ],
    ),
    EmojiCategory(
      id: 'food',
      label: 'Comida',
      icon: '🍕',
      emojis: [
        '🍏',
        '🍎',
        '🍐',
        '🍊',
        '🍋',
        '🍌',
        '🍉',
        '🍇',
        '🍓',
        '🫐',
        '🍈',
        '🍒',
        '🍑',
        '🥭',
        '🍍',
        '🥥',
        '🥝',
        '🍅',
        '🍆',
        '🥑',
        '🥦',
        '🥬',
        '🥒',
        '🌶️',
        '🫑',
        '🌽',
        '🥕',
        '🫒',
        '🧄',
        '🧅',
        '🥔',
        '🍠',
        '🥐',
        '🥯',
        '🍞',
        '🥖',
        '🥨',
        '🧀',
        '🥚',
        '🍳',
        '🧈',
        '🥞',
        '🧇',
        '🥓',
        '🥩',
        '🍗',
        '🍖',
        '🦴',
        '🌭',
        '🍔',
        '🍟',
        '🍕',
        '🫓',
        '🥪',
        '🥙',
        '🧆',
        '🌮',
        '🌯',
        '🫔',
        '🥗',
        '🥘',
        '🫕',
        '🥫',
        '🍝',
        '🍜',
        '🍲',
        '🍛',
        '🍣',
        '🍱',
        '🥟',
        '🦪',
        '🍤',
        '🍙',
        '🍚',
        '🍘',
        '🍥',
        '🥠',
        '🥮',
        '🍢',
        '🍡',
        '🍧',
        '🍨',
        '🍦',
        '🥧',
        '🧁',
        '🍰',
        '🎂',
        '🍮',
        '🍭',
        '🍬',
        '🍫',
        '🍿',
        '🍩',
        '🍪',
        '🌰',
        '🥜',
        '🍯',
        '🥛',
        '🍼',
        '🫖',
        '☕',
        '🍵',
        '🧃',
        '🥤',
        '🧋',
        '🍶',
        '🍺',
        '🍻',
        '🥂',
        '🍷',
        '🥃',
        '🍸',
        '🍹',
        '🧉',
        '🍾',
        '🧊',
        '🥄',
        '🍴',
        '🍽️',
        '🥣',
        '🥡',
        '🥢',
        '🧂',
      ],
    ),
    EmojiCategory(
      id: 'travel',
      label: 'Viagem',
      icon: '✈️',
      emojis: [
        '🚗',
        '🚕',
        '🚙',
        '🚌',
        '🚎',
        '🏎️',
        '🚓',
        '🚑',
        '🚒',
        '🚐',
        '🛻',
        '🚚',
        '🚛',
        '🚜',
        '🦯',
        '🦽',
        '🦼',
        '🛴',
        '🚲',
        '🛵',
        '🏍️',
        '🛺',
        '🚨',
        '🚔',
        '🚍',
        '🚘',
        '🚖',
        '🚡',
        '🚠',
        '🚟',
        '🚃',
        '🚋',
        '🚞',
        '🚝',
        '🚄',
        '🚅',
        '🚈',
        '🚂',
        '🚆',
        '🚇',
        '🚊',
        '🚉',
        '✈️',
        '🛫',
        '🛬',
        '🛩️',
        '💺',
        '🛰️',
        '🚀',
        '🛸',
        '🚁',
        '🛶',
        '⛵',
        '🚤',
        '🛥️',
        '🛳️',
        '⛴️',
        '🚢',
        '⚓',
        '🪝',
        '⛽',
        '🚧',
        '🚦',
        '🚥',
        '🚏',
        '🗺️',
        '🗿',
        '🗽',
        '🗼',
        '🏰',
        '🏯',
        '🏟️',
        '🎡',
        '🎢',
        '🎠',
        '⛲',
        '⛱️',
        '🏖️',
        '🏝️',
        '🏜️',
        '🌋',
        '⛰️',
        '🏔️',
        '🗻',
        '🏕️',
        '⛺',
        '🏠',
        '🏡',
        '🏢',
        '🏣',
        '🏤',
        '🏥',
        '🏦',
        '🏨',
        '🏩',
        '🏪',
        '🏫',
        '🏬',
        '🏭',
        '🏯',
        '💒',
        '🗼',
        '🗽',
        '⛪',
        '🕌',
        '🛕',
        '🕍',
        '⛩️',
        '🕋',
      ],
    ),
    EmojiCategory(
      id: 'objects',
      label: 'Objetos',
      icon: '💡',
      emojis: [
        '⌚',
        '📱',
        '📲',
        '💻',
        '⌨️',
        '🖥️',
        '🖨️',
        '🖱️',
        '🖲️',
        '🕹️',
        '🗜️',
        '💽',
        '💾',
        '💿',
        '📀',
        '📼',
        '📷',
        '📸',
        '📹',
        '🎥',
        '📽️',
        '🎞️',
        '📞',
        '☎️',
        '📟',
        '📠',
        '📺',
        '📻',
        '🎙️',
        '🎚️',
        '🎛️',
        '🧭',
        '⏱️',
        '⏲️',
        '⏰',
        '🕰️',
        '⌛',
        '⏳',
        '📡',
        '🔋',
        '🔌',
        '💡',
        '🔦',
        '🕯️',
        '🪔',
        '🧯',
        '🛢️',
        '💸',
        '💵',
        '💴',
        '💶',
        '💷',
        '🪙',
        '💰',
        '💳',
        '💎',
        '⚖️',
        '🪜',
        '🧰',
        '🪛',
        '🔧',
        '🔨',
        '⚒️',
        '🛠️',
        '⛏️',
        '🪚',
        '🔩',
        '⚙️',
        '🪤',
        '🧱',
        '⛓️',
        '🧲',
        '🔫',
        '💣',
        '🧨',
        '🪓',
        '🔪',
        '🗡️',
        '⚔️',
        '🛡️',
        '🚬',
        '⚰️',
        '🪦',
        '⚱️',
        '🏺',
        '🔮',
        '📿',
        '🧿',
        '💈',
        '⚗️',
        '🔭',
        '🔬',
        '🕳️',
        '🩹',
        '🩺',
        '💊',
        '💉',
        '🩸',
        '🧬',
        '🦠',
        '🧫',
        '🧪',
        '🌡️',
        '🧹',
        '🪠',
        '🧺',
        '🧻',
        '🚽',
        '🚰',
        '🚿',
        '🛁',
        '🛀',
        '🧼',
        '🪥',
        '🪒',
        '🧽',
        '🪣',
        '🧴',
        '🛎️',
        '🔑',
        '🗝️',
        '🚪',
        '🪑',
        '🛋️',
        '🛏️',
        '🛌',
        '🧸',
        '🪆',
        '🖼️',
        '🪞',
        '🪟',
        '🛍️',
        '🛒',
        '🎁',
        '🎈',
        '🎏',
        '🎀',
        '🪄',
        '🪅',
        '🎊',
        '🎉',
        '🎎',
        '🏮',
        '🎐',
        '🧧',
        '✉️',
        '📩',
        '📨',
        '📧',
        '💌',
        '📥',
        '📤',
        '📦',
        '🏷️',
        '🪧',
        '📪',
        '📫',
        '📬',
        '📭',
        '📮',
        '📯',
        '📜',
        '📃',
        '📄',
        '📑',
        '🧾',
        '📊',
        '📈',
        '📉',
        '🗒️',
        '🗓️',
        '📆',
        '📅',
        '🗑️',
        '📇',
        '🗃️',
        '🗳️',
        '🗄️',
        '📋',
        '📁',
        '📂',
        '🗂️',
        '🗞️',
        '📰',
        '📓',
        '📔',
        '📒',
        '📕',
        '📗',
        '📘',
        '📙',
        '📚',
        '📖',
        '🔖',
        '🧷',
        '🔗',
        '📎',
        '🖇️',
        '📐',
        '📏',
        '🧮',
        '📌',
        '📍',
        '✂️',
        '🖊️',
        '🖋️',
        '✒️',
        '🖌️',
        '🖍️',
        '📝',
        '✏️',
        '🔍',
        '🔎',
        '🔏',
        '🔐',
        '🔒',
        '🔓',
      ],
    ),
    EmojiCategory(
      id: 'symbols',
      label: 'Símbolos',
      icon: '❤️',
      emojis: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❣️',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '☮️',
        '✝️',
        '☪️',
        '🕉️',
        '☸️',
        '✡️',
        '🔯',
        '🕎',
        '☯️',
        '☦️',
        '🛐',
        '⛎',
        '♈',
        '♉',
        '♊',
        '♋',
        '♌',
        '♍',
        '♎',
        '♏',
        '♐',
        '♑',
        '♒',
        '♓',
        '🆔',
        '⚛️',
        '🉑',
        '☢️',
        '☣️',
        '📴',
        '📳',
        '🈶',
        '🈚',
        '🈸',
        '🈺',
        '🈷️',
        '✴️',
        '🆚',
        '💮',
        '🉐',
        '㊙️',
        '恭喜',
        '🈴',
        '🈵',
        '🈹',
        '🈲',
        '🅰️',
        '🅱️',
        '🆎',
        '🆑',
        '🅾️',
        '🆘',
        '❌',
        '⭕',
        '🛑',
        '⛔',
        '📛',
        '🚫',
        '💯',
        '💢',
        '♨️',
        '🚷',
        '🚯',
        '🚳',
        '🚱',
        '🔞',
        '📵',
        '🚭',
        '❗',
        '❕',
        '❓',
        '❔',
        '‼️',
        '⁉️',
        '🔅',
        '🔆',
        '〽️',
        '⚠️',
        '🚸',
        '🔱',
        '⚜️',
        '🔰',
        '♻️',
        '✅',
        '🈯',
        '💹',
        '❇️',
        '✳️',
        '❎',
        '🌐',
        '💠',
        'Ⓜ️',
        '🌀',
        '💤',
        '🏧',
        '🚾',
        '♿',
        '🅿️',
        '🛗',
        '🈳',
        '🈂️',
        '🛂',
        '🛃',
        '🛄',
        '🛅',
        '🚹',
        '🚺',
        '🚼',
        '⚧',
        '🚻',
        '🚮',
        '🎦',
        '📶',
        '🈁',
        '🔣',
        'ℹ️',
        '🔤',
        '🔡',
        '🔠',
        '🆖',
        '🆗',
        '🆙',
        '🆒',
        '🆕',
        '🆓',
        '0️⃣',
        '1️⃣',
        '2️⃣',
        '3️⃣',
        '4️⃣',
        '5️⃣',
        '6️⃣',
        '7️⃣',
        '8️⃣',
        '9️⃣',
        '🔟',
        '🔢',
        '#️⃣',
        '*️⃣',
        '⏏️',
        '▶️',
        '⏸️',
        '⏯️',
        '⏹️',
        '⏺️',
        '⏭️',
        '⏮️',
        '⏩',
        '⏪',
        '⏫',
        '⏬',
        '◀️',
        '🔼',
        '🔽',
        '➡️',
        '⬅️',
        '⬆️',
        '⬇️',
        '↗️',
        '↘️',
        '↙️',
        '↖️',
        '↕️',
        '↔️',
        '↪️',
        '↩️',
        '⤴️',
        '⤵️',
        '🔀',
        '🔁',
        '🔂',
        '🔄',
        '🔃',
        '🎵',
        '🎶',
        '➕',
        '➖',
        '➗',
        '✖️',
        '♾️',
        '💲',
        '💱',
        '™️',
        '©️',
        '®️',
        '👁️‍🗨️',
        '🔚',
        '🔙',
        '🔛',
        '🔝',
        '🔜',
        '〰️',
        '➰',
        '➿',
        '✔️',
        '☑️',
        '🔘',
        '🔴',
        '🟠',
        '🟡',
        '🟢',
        '🔵',
        '🟣',
        '⚫',
        '⚪',
        '🟤',
        '🔺',
        '🔻',
        '🔸',
        '🔹',
        '🔶',
        '🔷',
        '🔳',
        '🔲',
        '▪️',
        '▫️',
        '◾',
        '◽',
        '◼️',
        '◻️',
        '🟥',
        '🟧',
        '🟨',
        '🟩',
        '🟦',
        '🟪',
        '⬛',
        '⬜',
        '🟫',
        '🔈',
        '🔇',
        '🔉',
        '🔊',
        '🔔',
        '🔕',
        '📣',
        '📢',
        '💬',
        '💭',
        '🗯️',
        '♠️',
        '♣️',
        '♥️',
        '♦️',
        '🃏',
        '🎴',
        '🀄',
        '🕐',
        '🕑',
        '🕒',
        '🕓',
        '🕔',
        '🕕',
        '🕖',
        '🕗',
        '🕘',
        '🕙',
        '🕚',
        '🕛',
        '🕜',
        '🕝',
        '🕞',
        '🕟',
        '🕠',
        '🕡',
        '🕢',
        '🕣',
        '🕤',
        '🕥',
        '🕦',
        '🕧',
      ],
    ),
    EmojiCategory(
      id: 'flags',
      label: 'Bandeiras',
      icon: '🇧🇷',
      emojis: [
        '🏳️',
        '🏴',
        '🏁',
        '🚩',
        '🏳️‍🌈',
        '🏳️‍⚧️',
        '🇺🇳',
        '🇧🇷',
        '🇵🇹',
        '🇺🇸',
        '🇬🇧',
        '🇪🇸',
        '🇫🇷',
        '🇩🇪',
        '🇮🇹',
        '🇯🇵',
        '🇨🇳',
        '🇰🇷',
        '🇮🇳',
        '🇷🇺',
        '🇨🇦',
        '🇲🇽',
        '🇦🇷',
        '🇨🇱',
        '🇨🇴',
        '🇵🇪',
        '🇺🇾',
        '🇵🇾',
        '🇧🇴',
        '🇪🇨',
        '🇻🇪',
        '🇨🇺',
        '🇦🇺',
        '🇳🇿',
        '🇿🇦',
        '🇳🇬',
        '🇪🇬',
        '🇹🇷',
        '🇸🇦',
        '🇦🇪',
        '🇮🇱',
        '🇬🇷',
        '🇳🇱',
        '🇧🇪',
        '🇨🇭',
        '🇸🇪',
        '🇳🇴',
        '🇩🇰',
        '🇫🇮',
        '🇵🇱',
        '🇺🇦',
        '🇷🇴',
        '🇭🇺',
        '🇨🇿',
        '🇦🇹',
        '🇮🇪',
        '🇵🇭',
        '🇮🇩',
        '🇹🇭',
        '🇻🇳',
        '🇲🇾',
        '🇸🇬',
        '🇭🇰',
        '🇹🇼',
      ],
    ),
  ];

  static List<String> get all {
    final seen = <String>{};
    final out = <String>[];
    for (final category in categories) {
      for (final emoji in category.emojis) {
        if (seen.add(emoji)) out.add(emoji);
      }
    }
    return out;
  }
}

class EmojiCategory {
  const EmojiCategory({
    required this.id,
    required this.label,
    required this.icon,
    required this.emojis,
  });

  final String id;
  final String label;
  final String icon;
  final List<String> emojis;
}

Future<String?> showEmojiPickerSheet(
  BuildContext context, {
  Offset? anchor,
  bool reactionMode = false,
}) {
  if (anchor != null) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return showGeneralDialog<String>(
      context: context,
      barrierDismissible: true,
      barrierLabel: 'Fechar emojis',
      barrierColor: Colors.transparent,
      transitionDuration: const Duration(milliseconds: 140),
      pageBuilder: (context, animation, secondaryAnimation) {
        final screen = MediaQuery.sizeOf(context);
        final width = math.min(474.0, math.max(296.0, screen.width - 24));
        final height = math.min(374.0, math.max(300.0, screen.height - 36));
        final maxLeft = math.max(12.0, screen.width - width - 12);
        final maxTop = math.max(12.0, screen.height - height - 12);
        final left = (anchor.dx - width / 2).clamp(12.0, maxLeft).toDouble();
        var top = anchor.dy - height - 18;
        if (top < 12) top = anchor.dy + 14;
        top = top.clamp(12.0, maxTop).toDouble();
        return SafeArea(
          child: Stack(
            children: [
              Positioned.fill(
                child: GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: () => Navigator.of(context).pop(),
                ),
              ),
              Positioned(
                left: left,
                top: top,
                width: width,
                child: Material(
                  color: isDark ? const Color(0xFF1F2C33) : Colors.white,
                  elevation: 12,
                  shadowColor: Colors.black.withValues(alpha: 0.22),
                  borderRadius: BorderRadius.circular(18),
                  clipBehavior: Clip.antiAlias,
                  child: _EmojiPickerSheet(
                    panelHeight: height,
                    reactionMode: reactionMode,
                  ),
                ),
              ),
            ],
          ),
        );
      },
      transitionBuilder: (context, animation, secondaryAnimation, child) {
        final curved = CurvedAnimation(
          parent: animation,
          curve: Curves.easeOutCubic,
        );
        return FadeTransition(
          opacity: curved,
          child: ScaleTransition(
            scale: Tween<double>(begin: 0.96, end: 1).animate(curved),
            child: child,
          ),
        );
      },
    );
  }

  return showBotAdminBottomSheet<String>(
    context: context,
    isScrollControlled: true,
    showDragHandle: true,
    backgroundColor: Theme.of(context).brightness == Brightness.dark
        ? const Color(0xFF1F2C33)
        : Colors.white,
    builder: (context) => const _EmojiPickerSheet(),
  );
}

/// Barra flutuante de reações no estilo WhatsApp oficial
/// (cápsula com 6 emojis + botão “+”).
Future<String?> showReactionPicker(BuildContext context, {Offset? position}) {
  final isDark = Theme.of(context).brightness == Brightness.dark;
  final barBg = isDark ? const Color(0xFF233138) : Colors.white;
  final moreBg = isDark ? const Color(0xFF2A3942) : const Color(0xFFF0F2F5);
  final moreFg = isDark ? const Color(0xFFAEBAC1) : const Color(0xFF54656F);

  return showGeneralDialog<String>(
    context: context,
    barrierDismissible: true,
    barrierLabel: 'Fechar reações',
    barrierColor: Colors.transparent,
    transitionDuration: const Duration(milliseconds: 160),
    pageBuilder: (context, animation, secondaryAnimation) {
      final screen = MediaQuery.sizeOf(context);
      final width = math.min(326.0, math.max(296.0, screen.width - 24));
      const height = 58.0;
      final anchor = position ?? Offset(screen.width / 2, screen.height / 2);
      final maxLeft = math.max(12.0, screen.width - width - 12);
      final maxTop = math.max(12.0, screen.height - height - 12);
      final left = (anchor.dx - width / 2).clamp(12.0, maxLeft).toDouble();
      var top = anchor.dy - height - 14;
      if (top < 12) top = anchor.dy + 12;
      top = top.clamp(12.0, maxTop).toDouble();
      return SafeArea(
        child: Stack(
          children: [
            Positioned.fill(
              child: GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: () => Navigator.of(context).pop(),
              ),
            ),
            Positioned(
              left: left,
              top: top,
              child: Material(
                color: Colors.transparent,
                child: DecoratedBox(
                  decoration: BoxDecoration(
                    color: barBg,
                    borderRadius: BorderRadius.circular(999),
                    boxShadow: const [
                      BoxShadow(
                        color: Color(0x40000000),
                        blurRadius: 18,
                        offset: Offset(0, 8),
                      ),
                    ],
                  ),
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(8, 7, 8, 7),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        for (final emoji in EmojiCatalog.quickReactions)
                          _WhatsAppReactionEmoji(
                            emoji: emoji,
                            onTap: () => Navigator.of(context).pop(emoji),
                          ),
                        const SizedBox(width: 2),
                        Material(
                          color: moreBg,
                          shape: const CircleBorder(),
                          child: InkWell(
                            customBorder: const CircleBorder(),
                            onTap: () async {
                              final more = await showEmojiPickerSheet(
                                context,
                                anchor: Offset(left + width / 2, top),
                                reactionMode: true,
                              );
                              if (context.mounted && more != null) {
                                Navigator.of(context).pop(more);
                              }
                            },
                            child: SizedBox(
                              width: 40,
                              height: 40,
                              child: Icon(
                                Icons.add_rounded,
                                color: moreFg,
                                size: 24,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      );
    },
    transitionBuilder: (context, animation, secondaryAnimation, child) {
      final curved = CurvedAnimation(
        parent: animation,
        curve: Curves.easeOutBack,
      );
      return FadeTransition(
        opacity: animation,
        child: ScaleTransition(
          scale: Tween<double>(begin: 0.86, end: 1).animate(curved),
          child: child,
        ),
      );
    },
  );
}

class _WhatsAppReactionEmoji extends StatefulWidget {
  const _WhatsAppReactionEmoji({required this.emoji, required this.onTap});

  final String emoji;
  final VoidCallback onTap;

  @override
  State<_WhatsAppReactionEmoji> createState() => _WhatsAppReactionEmojiState();
}

class _WhatsAppReactionEmojiState extends State<_WhatsAppReactionEmoji> {
  bool _pressed = false;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTapDown: (_) => setState(() => _pressed = true),
      onTapCancel: () => setState(() => _pressed = false),
      onTapUp: (_) => setState(() => _pressed = false),
      onTap: widget.onTap,
      child: AnimatedScale(
        scale: _pressed ? 1.22 : 1,
        duration: const Duration(milliseconds: 100),
        child: SizedBox(
          width: 44,
          height: 44,
          child: Center(child: Text(widget.emoji, style: emojiTextStyle(28))),
        ),
      ),
    );
  }
}

class _EmojiPickerSheet extends StatefulWidget {
  const _EmojiPickerSheet({this.panelHeight, this.reactionMode = false});

  final double? panelHeight;
  final bool reactionMode;

  @override
  State<_EmojiPickerSheet> createState() => _EmojiPickerSheetState();
}

class _EmojiPickerSheetState extends State<_EmojiPickerSheet> {
  int _index = 0;
  final _search = TextEditingController();

  @override
  void dispose() {
    _search.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final category = EmojiCatalog.categories[_index];
    final height =
        widget.panelHeight ?? MediaQuery.sizeOf(context).height * 0.62;
    final query = _search.text.trim();
    final emojis = query.isEmpty
        ? category.emojis
        : EmojiCatalog.all.where((emoji) => emoji.contains(query)).toList();
    final label = query.isNotEmpty
        ? 'Resultados'
        : widget.reactionMode && _index == 0
        ? 'Smileys e pessoas'
        : category.label;

    return SafeArea(
      child: SizedBox(
        height: height,
        child: Column(
          children: [
            SizedBox(
              height: 52,
              child: ListView.separated(
                padding: const EdgeInsets.fromLTRB(14, 7, 14, 3),
                scrollDirection: Axis.horizontal,
                itemCount: EmojiCatalog.categories.length,
                separatorBuilder: (_, _) => const SizedBox(width: 6),
                itemBuilder: (context, i) {
                  final cat = EmojiCatalog.categories[i];
                  final selected = i == _index;
                  return Material(
                    color: Colors.transparent,
                    child: InkWell(
                      borderRadius: BorderRadius.circular(10),
                      onTap: () => setState(() => _index = i),
                      child: SizedBox(
                        width: 42,
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(
                              _categoryIcon(cat.id),
                              size: 24,
                              color: isDark
                                  ? const Color(0xFFD1D7DB)
                                  : const Color(0xFF54656F),
                            ),
                            const SizedBox(height: 5),
                            AnimatedContainer(
                              duration: const Duration(milliseconds: 120),
                              width: selected ? 32 : 0,
                              height: 3,
                              decoration: BoxDecoration(
                                color: isDark
                                    ? const Color(0xFFE9EDEF)
                                    : const Color(0xFF111B21),
                                borderRadius: BorderRadius.circular(999),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(18, 8, 18, 8),
              child: SizedBox(
                height: 46,
                child: TextField(
                  controller: _search,
                  onChanged: (_) => setState(() {}),
                  style: TextStyle(
                    color: isDark
                        ? const Color(0xFFE9EDEF)
                        : const Color(0xFF111B21),
                    fontSize: 15,
                  ),
                  decoration: InputDecoration(
                    hintText: widget.reactionMode
                        ? 'Pesquisar reação'
                        : 'Pesquisar emoji',
                    prefixIcon: const Icon(Icons.search_rounded),
                    filled: true,
                    fillColor: isDark ? const Color(0xFF111B21) : Colors.white,
                    contentPadding: EdgeInsets.zero,
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(999),
                      borderSide: BorderSide(
                        color: isDark
                            ? const Color(0xFF8696A0)
                            : const Color(0xFF111B21),
                        width: 2,
                      ),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(999),
                      borderSide: BorderSide(
                        color: isDark
                            ? const Color(0xFF8696A0)
                            : const Color(0xFF111B21),
                        width: 2,
                      ),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(999),
                      borderSide: const BorderSide(
                        color: Color(0xFF00A884),
                        width: 2,
                      ),
                    ),
                  ),
                ),
              ),
            ),
            if (widget.reactionMode && query.isEmpty) ...[
              _EmojiSectionLabel('Reações recentes', isDark: isDark),
              SizedBox(
                height: 48,
                child: ListView(
                  padding: const EdgeInsets.symmetric(horizontal: 18),
                  scrollDirection: Axis.horizontal,
                  children: [
                    for (final emoji in const ['😢', '😂', '❤️', '👍'])
                      _EmojiGridButton(emoji: emoji, size: 32),
                  ],
                ),
              ),
            ],
            _EmojiSectionLabel(label, isDark: isDark),
            Expanded(
              child: LayoutBuilder(
                builder: (context, constraints) {
                  final columns = (constraints.maxWidth / 45).floor().clamp(
                    6,
                    10,
                  );
                  return GridView.builder(
                    padding: const EdgeInsets.fromLTRB(14, 4, 14, 18),
                    gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: columns,
                      mainAxisSpacing: 5,
                      crossAxisSpacing: 5,
                    ),
                    itemCount: emojis.length,
                    itemBuilder: (context, index) {
                      return _EmojiGridButton(emoji: emojis[index], size: 29);
                    },
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _EmojiSectionLabel extends StatelessWidget {
  const _EmojiSectionLabel(this.label, {required this.isDark});

  final String label;
  final bool isDark;

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(18, 6, 18, 7),
        child: Text(
          label,
          style: TextStyle(
            color: isDark ? const Color(0xFF8696A0) : const Color(0xFF667781),
            fontWeight: FontWeight.w800,
            fontSize: 14,
          ),
        ),
      ),
    );
  }
}

class _EmojiGridButton extends StatelessWidget {
  const _EmojiGridButton({required this.emoji, required this.size});

  final String emoji;
  final double size;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      borderRadius: BorderRadius.circular(10),
      onTap: () => Navigator.of(context).pop(emoji),
      child: Center(child: Text(emoji, style: emojiTextStyle(size))),
    );
  }
}

IconData _categoryIcon(String id) {
  switch (id) {
    case 'smileys':
      return Icons.emoji_emotions_outlined;
    case 'gestures':
      return Icons.back_hand_outlined;
    case 'people':
      return Icons.diversity_3_outlined;
    case 'animals':
      return Icons.pets_outlined;
    case 'food':
      return Icons.local_cafe_outlined;
    case 'travel':
      return Icons.directions_car_outlined;
    case 'objects':
      return Icons.lightbulb_outline_rounded;
    case 'symbols':
      return Icons.currency_exchange_rounded;
    case 'flags':
      return Icons.flag_outlined;
    default:
      return Icons.emoji_symbols_outlined;
  }
}
